---
driver:
  name: vagrant

provisioner:
  name: chef_solo

platforms:
  - name: centos-7.1
    driver_config:
      box: opscode-centos-7.1
      box_url: http://opscode-vm-bento.s3.amazonaws.com/vagrant/virtualbox/opscode_centos-7.1_chef-provisionerless.box

suites:
  - name: mongodb
    data_bags_path: "test/integration/data_bags"
    sudo: true
    run_list:
      - role[mongodb_single]
    attributes:
