#cloud-config

bootcmd:
 - echo 127.0.1.1 zk3 >> /etc/hosts
 - hostname zk3
 - [ cloud-init-per, once, data-store, mkfs.ext4, /dev/xvdb ]

mounts:
- [ xvdb, /mnt, ext4 ]
- [ ephemeral0, /eph0, auto, "defaults,noexec" ]
- [ ephemeral1, none, swap ]

preserve_hostname: true
